### ISSUE TITLE
file type filtering

### ISSUE THREAD

**Issue by Leenshady** [Johann-S/bs-custom-file-input#41]
Does this plug-in provide file type filtering?

**Comment by jessycormier** [comment]
+1

**Comment by Leenshady** [comment]
Thank you for your reply. I'm sorry for my misrepresentation. I mean when I submit a file of the wrong type, there will be friendly prompts.

**Comment by Leenshady** [comment]
I'm not familiar with the front end. If my requirement are wrong, please don't hit me, hahahaha

**Comment by jessycormier** [comment]
There would be two layers that you would need to check. First being your front-end, which you can do with the provided example or by writing some code that can check the file types and prevent uploading.

The other layer would be your server, after receiving the file that is acceptable. otherwise you could return some kind of server response to your front-end.

**Comment by Leenshady** [comment]
So I can't do this only on the front-end,right?thank you very much!

**Comment by Johann-S** [comment]
Hi @Leenshady, it's not the purpose of this plugin and as @jessycormier said it's not a good practice to do that only on the front side.
BTW thanks for using my plugin and thanks @jessycormier for answering 👍
