### ISSUE TITLE
Feature: Indicate source from server side.

### ISSUE THREAD

**Issue by LocalHeroPro** [Johann-S/bs-custom-file-input#58]
Can we indicate source for choosing file from server folder?

**Comment by Johann-S** [comment]
Hi @LocalHeroPro,

Sorry I don't understand your feature 😟 
What do you mean by "indicate the source for choosing file"?

**Comment by LocalHeroPro** [comment]
In normal way when you click on `Browse` button, you choose files to upload from your - for example - local storage. I want after click `Browse` see files what are already uploaded to the server and from that collection pick up some files and in input have path to that files. After press submit button I can manage that paths as I want to...

**Comment by Johann-S** [comment]
Oh ok I see!
That's a huge feature, I don't think it's the purpose of `bs-custom-file-input`, because it'll need to add a kind of modal to select files inside and allow to pass a list of files.

But I think it should be useful to your use case if `bs-custom-file-input` allows you to put values in the input.

**Comment by LocalHeroPro** [comment]
OK. Thanks for answer.
I'll close that topic.
